sonar.projectKey=ghes:CAI-Developer-Experience_test-rotate-sqapi:test-rotate-sqapi
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.language=py

# Exclude files that are not meaningful for static analysis
sonar.exclusions=**/*.yaml,**/*.yml,**/Dockerfile,**/*.txt,**/*.md,**/*.sh,**/.gitkeep

# Do not fail the quality gate due to missing coverage on a project with no test code
sonar.coverage.exclusions=**/*
